### ISSUE TITLE
npm install (node-sass@3.8.0 install node_modules/node-sass)

### ISSUE THREAD

**Issue by denegny** [ck3g/prater#8]
`> node-sass@3.8.0 install node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/linux-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.8.0 postinstall node_modules/node-sass
> node scripts/build.js`

install node-sass via 

> npm install node-sass

and after start phx server get log

`19:09:07 - info: Installing packages with npm...
[info] GET /sessions/new
[debug] Processing with PraterWeb.SessionController.new/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 199ms
[info] GET /css/app.css
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /css/app.css (PraterWeb.Router)
    (prater) lib/prater_web/router.ex:1: PraterWeb.Router.__match_route__/4
    (prater) lib/phoenix/router.ex:303: PraterWeb.Router.call/2
    (prater) lib/prater_web/endpoint.ex:1: PraterWeb.Endpoint.plug_builder_call/2
    (prater) lib/plug/debugger.ex:99: PraterWeb.Endpoint."call (overridable 3)"/2
    (prater) lib/prater_web/endpoint.ex:1: PraterWeb.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) prater/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

19:09:16 - warn: Loading of sass-brunch failed due to Cannot find module '/prater/assets/node_modules/sass-brunch'`

**Comment by ck3g** [comment]
Hey @denegny 

could you please provide version numbers of the Node.js and npm?

I've found this issue https://github.com/sass/node-sass/issues/2034 but I'm not sure that is related.

**Comment by denegny** [comment]
> $ node -v
> v9.6.1
> $ npm -v
> 5.0.3

both install via asdf

**Comment by ck3g** [comment]
I didn't manage to reproduce it. =(

Did you follow the [How to try it out](https://github.com/ck3g/prater#how-to-try-it-out) steps from readme? If not could you please try it.

If that didn't work, I will try to think about other solution. Maybe will try to wrap that into a docker image.

**Comment by denegny** [comment]
thanks
